title: My Project Documentation
email: your-email@example.com
description: A comprehensive guide for my awesome project.
# Use a theme supported by GitHub Pages
makrdown: kramdown
theme: jekyll-theme-cayman
